---
# Regions
# --------
# San Francisco 1 (id: 3)
# New York 2 (id: 4)
# Amsterdam 2 (id: 5)
# Singapore 1 (id: 6)
#
# Images
# ------
# CentOS 5.8 x64 (id: 1601, distro: CentOS)
# CentOS 5.8 x32 (id: 1602, distro: CentOS)
# Debian 6.0 x64 (id: 12573, distro: Debian)
# Debian 6.0 x32 (id: 12575, distro: Debian)
# Ubuntu 10.04 x64 (id: 14097, distro: Ubuntu)
# Ubuntu 10.04 x32 (id: 14098, distro: Ubuntu)
# Fedora 17 x32 (id: 32387, distro: Fedora)
# Fedora 17 x32 Desktop (id: 32399, distro: Fedora)
# Fedora 17 x64 Desktop (id: 32419, distro: Fedora)
# Fedora 17 x64 (id: 32428, distro: Fedora)
# Debian 7.0 x32 (id: 303619, distro: Debian)
# Debian 7.0 x64 (id: 308287, distro: Debian)
# Ubuntu 13.04 x32 (id: 345791, distro: Ubuntu)
# Ubuntu 13.04 x64 (id: 350076, distro: Ubuntu)
# Arch Linux 2013.05 x64 (id: 350424, distro: Arch Linux)
# Arch Linux 2013.05 x32 (id: 361740, distro: Arch Linux)
# CentOS 6.4 x32 (id: 376568, distro: CentOS)
# Ubuntu 12.10 x32 (id: 433240, distro: Ubuntu)
# LAMP on Ubuntu 12.04 (id: 459444, distro: Ubuntu)
# Ubuntu 12.10 x64 (id: 473123, distro: Ubuntu)
# Ubuntu 12.10 x64 Desktop (id: 473136, distro: Ubuntu)
# CentOS 6.4 x64 (id: 562354, distro: CentOS)
# Fedora 19 x64 (id: 696598, distro: Fedora)
# Fedora 19 x32 (id: 697056, distro: Fedora)
# Ubuntu 13.10 x32 (id: 962304, distro: Ubuntu)
# MEAN on Ubuntu 12.04.3 (id: 1420643, distro: Ubuntu)
# Ubuntu 12.04.3 x64 (id: 1505447, distro: Ubuntu)
# Ubuntu 12.04.3 x32 (id: 1505527, distro: Ubuntu)
# Ubuntu 13.10 x64 (id: 1505699, distro: Ubuntu)
# Ruby on Rails on Ubuntu 12.10 (Nginx + Unicorn) (id: 1608711, distro: Ubuntu)
# CentOS 6.5 x64 (id: 1646467, distro: CentOS)
# CentOS 6.5 x32 (id: 1646732, distro: CentOS)
# Redmine on Ubuntu 12.04 (id: 1687372, distro: Ubuntu)
# Ghost 0.4.0 on Ubuntu 12.04 (id: 1860934, distro: Ubuntu)
# GitLab 6.5.1 CE (id: 2105243, distro: Ubuntu)
# Dokku-v0.2.1 on Ubuntu 13.04 (id: 2118237, distro: Ubuntu)
# Docker 0.8 Ubuntu 13.04 x64 (id: 2158507, distro: Ubuntu)
# Wordpress on Ubuntu 13.10 (id: 2377834, distro: Ubuntu)
#
# Sizes
# -----
# 512MB (id: 66)
# 1GB (id: 63)
# 2GB (id: 62)
# 4GB (id: 64)
# 8GB (id: 65)
# 16GB (id: 61)
# 32GB (id: 60)
# 48GB (id: 70)
# 64GB (id: 69)


# For now only allow this settings:
# - name: the name of the instance
# - Image: The image to load in the new instance
# - size: the type of instance (ram, cpu, disk...)
# - region: where to create the instance
# - wait: wait until is up (usefull if you are doing any work on these machines afterwards)
# - ssh_key_id: the ssh key id (previously stored in DO) 

# describe the instances to create:

instances:
  - name: development.test.1
    image: 1505447
    size: 66
    region: 5
    # Be aware of no space between them
    ssh_keys: "95309,95312"